version: '3.3'

services:

  readthedocs:
    user: ${UID:-1000}
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "8088:8088"
    links:
      - redis
    volumes:
      # mount docker unix socket to be able to run containers in the host from inside this container
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app
      - type: bind
        source: user_builds
        target: /app/user/builds
    environment:
      DJANGO_SETTINGS_MODULE: readthedocs.settings.docker
      DJANGO_SETTINGS_SKIP_LOCAL: 1


  # DEPENDENCIES

  redis:
    image: redis

  volumes:
    user_builds:

  # TODO: run celery workers
